const fertilizers = [
    { name: "Nitric acid (38%) (liquid)", formula: "HNO3" },
    { name: "Nitric acid (60%) (liquid)", formula: "HNO3" },
    { name: "Phosphoric acid (59%) (liquid)", formula: "H3PO4" },
    { name: "Potassium bicarbonate", formula: "KHCO3" },
    { name: "Ammonium nitrate (liquid)", formula: "NH4NO3" },
    { name: "Monoammoniumphosphate", formula: "NH4H2PO4" },
    { name: "Urea", formula: "CO(NH2)2" },
    { name: "Urea phosphate", formula: "CO(NH2)2·H3PO4" },
    { name: "Calcium nitrate (solid)", formula: "Ca(NO3)2·4H2O" },
    { name: "Calcium nitrate (liquid)", formula: "Ca(NO3)2" },
    { name: "Calcium chloride (solid)", formula: "CaCl2" },
    { name: "Calcium chloride (liquid)", formula: "CaCl2" },
    { name: "Monopotassium phosphate", formula: "KH2PO4" },
    { name: "Potassium nitrate", formula: "KNO3" },
    { name: "Potassium sulfate", formula: "K2SO4" },
    { name: "Potassium chloride", formula: "KCl" },
    { name: "Magnesium sulphate", formula: "MgSO4·7H2O" },
    { name: "Magnesium nitrate", formula: "Mg(NO3)2·6H2O" },
    { name: "Magnesium nitrate (liquid)", formula: "Mg(NO3)2" },
    { name: "Iron chelate (Fe-EDTA)", formula: "C10H12FeN2O8" },
    { name: "Iron chelate (Fe-DTPA)", formula: "C14H23FeN3O10" },
    { name: "Iron chelate (Fe-EDDHA)", formula: "C18H16FeN2O6" },
    { name: "Iron chelate (Fe-HBED)", formula: "C19H18FeN2O6" },
    { name: "Manganese chelate", formula: "Mn-EDTA" },
    { name: "Zinc chelate", formula: "Zn-EDTA" },
    { name: "Copper chelate", formula: "Cu-EDTA" },
    { name: "Manganese sulphate", formula: "MnSO4·H2O" },
    { name: "Zinc sulphate", formula: "ZnSO4·7H2O" },
    { name: "Boric acid", formula: "H3BO3" },
    { name: "Borax", formula: "Na2B4O7·10H2O" },
    { name: "Copper sulphate", formula: "CuSO4·5H2O" },
    { name: "Sodium molybdate", formula: "Na2MoO4·2H2O" }
];